/**
 * Stripe Plugin
 * Generated by imajin-cli Self-Extension System
 */

export const name = 'stripe';
export const version = '1.0.0';
export const description = 'Stripe integration plugin';

export * from './StripeService.js';
export * from './commands/ListCommand.js';
